---
galaxy_info:
  role_name: apache
  namespace: gpte
  author: GPTE Team
  description: Molecule demo apache role
  company: Red Hat
  version: 1.0.0
  license: license (GPL-3.0)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
  galaxy_tags:
    - apache
